---
- name: Lab10 - S4 - Playbook for SM using roles
  hosts: linux
  become: true
  roles:
    # - datadisk
    # - system_profile
    - users
  # environment:
  #   ANSIBLE_CONFIG: "/mnt/c/Users/12365/Downloads/Automation/Assignment/J/ansible/ansible.cfg"
